# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff031a18f2eb4fcaedb7e241383bdcf93750332a06f538b3f4733a538d0b47b5c8dceb2640cad7a63a6ec85d0239d5358b1923e85729208f59b900cd91d511bf

test:
  secret_key_base: 2cff6f42ec34edc6d23c7de51b6790a8b49f89052fd48a968358b44b019113f148868dc0979e0a07595eb4f6ffb2b204f006994e84102e2f8ee1250649f605e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
